<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>

    <AssemblyName>TimedCraftSpeed</AssemblyName>
    <RootNamespace>TimedCraftSpeed</RootNamespace>

    <Version>1.0.5</Version>
    <FileVersion>1.0.5.0</FileVersion>
    <AssemblyVersion>1.0.5.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="0Harmony">
      <HintPath>N:\MODS\r2modman\r2modmanPlus-local\Valheim\profiles\valheim\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="BepInEx">
      <HintPath>N:\MODS\r2modman\r2modmanPlus-local\Valheim\profiles\valheim\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>O:\Steam\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>O:\Steam\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>O:\Steam\steamapps\common\Valheim\valheim_Data\Managed\assembly_valheim.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>

</Project>





